#:kivy 1.11.1

<SightingTooltip>:
    orientation: "vertical"
    center: self.layout_pos
    canvas:
        Rectangle:
            pos: self.canvas_pos
            size: 200,100
    Label:
        text: "A cat spotted here!"
        color: 0, 0, 0, 1
    LabelDesc:
        text: "25 minutes ago."
        color: 0, 0, 0, 1
    BoxLayout:
        orientation: "horizontal"
        Button:
            text: "See More Detail"

<MapWidget>: