#:kivy 1.11.1

<SightingTooltip>:
    orientation: "vertical"
    center: self.layout_pos
    canvas:
        Rectangle:
            pos: self.canvas_pos
            size: 200,100
    LabelAnName:
        id: "animal_name"
        text: "This is a {animal}"
        color: 0, 0, 0, 1
    LabelDesc:
        text: "This is the main sighting description"
        color: 0, 0, 0, 1
    BoxLayout:
        orientation: "horizontal"
        Button:
            text: "See More Detail"

<MapWidget>: